baseURL = "http://blog.edelgrace.me/"
languageCode = "en-us"

# meta
title = "edelgrace.me"
description = "Blog of a nerdy crafter"
keywords = ["crochet", "knitting", "technology", "programming", "web dev"]

# theme
theme = "cocoa"

# archetypeDir =                "archetypes"

# include content marked as draft
# buildDrafts =                 false

# include content with publishdate in the future
buildFuture =                 false

# include content already expired
buildExpired =                false

# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs =                false
canonifyURLs =                false

# config file (default is path/config.yaml|json|toml)
config =                     "config.toml"
contentDir =                  "content"
dataDir =                     "data"
defaultExtension =            "html"
defaultLayout =               "post"

# Missing translations will default to this content language
defaultContentLanguage =      "en"

# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir =  false
disableLiveReload =           false

# Enable GitInfo feature
enableGitInfo =               false

# Build robots.txt file
enableRobotsTXT =             false

# Do not inject generator meta tag on homepage
disableHugoGeneratorInject =  false

# Allows you to disable all page types and will render nothing related to 'kind';
# values = "page", "home", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"
disableKinds = []

# Do not make the url/path to lowercase
disablePathToLower =          false

# Enable Emoji emoticons support for page content; see emoji-cheat-sheet.com
enableEmoji =                 false

# Show a placeholder instead of the default value or an empty string if a translation is missing
enableMissingTranslationPlaceholders = false
footnoteAnchorPrefix =        ""
footnoteReturnLinkContents =  ""

# google analytics tracking id
googleAnalytics =             ""

# if true, auto-detect Chinese/Japanese/Korean Languages in the content. (.Summary and .WordCount can work properly in CJKLanguage)
hasCJKLanguage =              false
layoutDir =                   "layouts"

# Enable Logging
log =                         true

# Log File path (if set, logging enabled automatically)
logFile = "logs/logs.txt"

# maximum number of items in the RSS feed
rssLimit =                    15

# "toml","yaml", or "json"
metaDataFormat =              "toml"
newContentEditor =            ""

# Don't sync permission mode of files
noChmod =                     false

# Don't sync modification time of files
noTimes =                     false

# Pagination
paginate =                    11
paginatePath =                "page"

# Pluralize titles in lists using inflect
pluralizeListTitles =         true

# Preserve special characters in taxonomy names ("Gérard Depardieu" vs "Gerard Depardieu")
preserveTaxonomyNames =       false

# filesystem path to write files to
publishDir = "public"

# enables syntax guessing for code fences without specified language
pygmentsCodeFencesGuessSyntax = false

# color-codes for highlighting derived from this style
pygmentsStyle =               "monokai"

# true: use pygments-css or false: color-codes directly
pygmentsUseClasses =          false

# see "Section Menu for Lazy Bloggers", /templates/menu-templates for more info
# SectionPagesMenu =

# default sitemap configuration map
# sitemap =

# filesystem path to read files relative from
# source =                      ""
# staticDir =                   "static"

# display memory and timing of different steps of the program
stepAnalysis =                false

# if true, use /filename.html instead of /filename/
uglyURLs =                    false

# verbose output
verbose =                     false

# verbose logging
verboseLog =                  false

# watch filesystem for changes and recreate as needed
watch =                       true

[taxonomies]
  category = "categories"
  tag = "tags"

[params]

[params.highlight]
style = "monokai"
languages = ["go", "dockerfile", "php", "python", "java"]

[[params.social]]
url = "https://github.com/edelgrace"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/edelgraceme"
fa_icon = "fa-twitter"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"